version: '3'
services:
  ad_engine:
    build: ./AD_Engine.java
    ports:
      - "8080:8080"

    networks:
      - my_custom_network

  ad_registry:
    build: ./ad_registry
    ports:
      - "8090:8090"
      MONGO_URI: mongodb://mongo:27017
    networks:
      - my_custom_network


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_custom_network

    volumes: 
      - mongo-data: /data/db

networks:
  my_custom_network:
volumes:
  mongo-data:
