version: '3'
services:
  engine:
    build:
      context: .
      dockerfile: Engine.DockerFile
    ports:
      - "3001:3001"
    container_name: engine
    command: sleep infinity
    environment:
      IP_BBDD: 192.168.23.1
      IP_SERVER_GESTOR: 192.168.23.1
      IP_ENGINE: 0.0.0.0
      PUERTO_SERVER_GESTOR: 29092
      PUERTO_ESCUCHA: 3001
      PUERTO_BBDD: 27017
      TOPIC_CONSUMIDOR: "drones_engine"
      TOPIC_PRODUCTOR: "engine_drones"
      
  registry:
    build:
      context: .
      dockerfile: Registry.DockerFile
    ports:
      - "3002:3002"
    command: python AD_Registry.py
    environment:
      IP_REGISTRY: 0.0.0.0
      PORT_BBDD: 27017
      PORT_REGISTRY: 3002
    container_name: registry

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo

  drone:
    build:
      context: .
      dockerfile: Drone2.DockerFile
    environment:
      IP: 192.168.23.1
      PORT_ENGINE: 3001
      PORT: 3002
      PORT_KAFKA: 29092
      CLAVE_ENCRIPTADA: "uErhONBMnC59GDVi71D3c3FySlDVbjokNCOkcXuIWWo="

    command: python AD_Drone.py
    container_name: dron
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    container_name: zookeeper
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.23.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    container_name: kafka
    